In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

# Cargar dataset Iris
iris = datasets.load_iris()
X = iris.data
y = iris.target
target_names = iris.target_names

# Dividir en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Crear modelo SVM con kernel lineal (porque Iris es casi linealmente separable)
# Cambios: podemos probar kernel='rbf' o ajustar C (parámetro de regularización)
modelo_svm = SVC(kernel='linear', C=1.0, random_state=42)

# Entrenar
modelo_svm.fit(X_train, y_train)

# Predicciones
y_pred = modelo_svm.predict(X_test)

# Evaluación
print("Reporte de clasificación SVM lineal:")
print(classification_report(y_test, y_pred, target_names=target_names))

# Matriz de confusión
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusión:\n", cm)

# Cambio para una aplicación: si queremos mejorar la precisión para datos más complejos,
# podemos usar kernel RBF y ajustar C y gamma mediante búsqueda en cuadrícula.
# Ejemplo:
# modelo_svm_rbf = SVC(kernel='rbf', C=10, gamma='scale')
# modelo_svm_rbf.fit(X_train, y_train)
# y_pred_rbf = modelo_svm_rbf.predict(X_test)

Reporte de clasificación SVM lineal:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Matriz de confusión:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
